---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oshelm.fullname" . }}
  labels:
    {{- include "oshelm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deutschebahn.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxSurge: 100%, maxUnavailable: 0}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oshelm.name" . }}
      app.kubernetes.io/instance: {{ include "oshelm.fullname" . }}
      application: {{ include "oshelm.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oshelm.name" . }}
        app.kubernetes.io/instance: {{ include "oshelm.fullname" . }}
        application: {{ include "oshelm.fullname" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ $.Values.deutschebahn.config.app.port | quote }}
        prometheus.io/path: /metrics
    spec:
      {{- with .Values.deutschebahn.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: exporter
          image: "{{ .Values.deutschebahn.image.name }}:{{ .Values.deutschebahn.image.tag }}"
          imagePullPolicy: {{ .Values.deutschebahn.image.pullPolicy }}
          env:
            - name: DB_CLIENT_ID
              value: {{ .Values.deutschebahn.DB_CLIENT_ID | quote}}
            - name: DB_CLIENT_SECRET
              value: {{ .Values.deutschebahn.DB_CLIENT_SECRET | quote}}
            - name: KEEP_MINUTES
              value: {{ .Values.deutschebahn.KEEP_MINUTES | quote }}
            - name: DB_STATION
              value: {{ .Values.deutschebahn.DB_STATION | quote }}
            - name: PORT
              value: {{ $.Values.deutschebahn.config.app.port | quote }}
            - name: POD_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            {{- toYaml .Values.deutschebahn.resources | nindent 12 }}
          readinessProbe:
            {{- with .Values.deutschebahn.healthcheck_url }}
            httpGet:
              path: {{ $.Values.deutschebahn.healthcheck_url }}
              port: {{ $.Values.deutschebahn.config.app.port }}
              scheme: HTTP
            {{- else }}
            tcpSocket:
              port: {{ $.Values.deutschebahn.config.app.port }}
            {{- end }}
            initialDelaySeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 5
          livenessProbe:
            {{- with .Values.deutschebahn.healthcheck_url }}
            httpGet:
              path: {{ $.Values.deutschebahn.healthcheck_url }}
              port: {{ $.Values.deutschebahn.config.app.port }}
              scheme: HTTP
            {{- else }}
            tcpSocket:
              port: {{ $.Values.deutschebahn.config.app.port }}
            {{- end }}
            initialDelaySeconds: 5
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
