{{- if .Values.deutschebahn.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oshelm.fullname" . }}
  labels:
    {{- include "oshelm.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.deutschebahn.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: "nginx"
  rules:
  {{- range .Values.deutschebahn.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "oshelm.fullname" $ }}
            port:
              number: {{ $.Values.deutschebahn.config.app.port }}
  {{- end }}
{{- end }}
